# Generated by Django 3.2.9 on 2022-04-15 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onetwo', '0002_auto_20220415_1438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='videos',
            field=models.FileField(upload_to='video/%y'),
        ),
    ]
